# Generated by Django 4.2 on 2026-05-12 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='申请标题')),
                ('content', models.JSONField(default=dict, verbose_name='申请内容')),
                ('status', models.CharField(choices=[('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='状态')),
                ('current_step', models.IntegerField(default=1, verbose_name='当前步骤')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_instances', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '审批实例',
                'verbose_name_plural': '审批实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='流程说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批流程模板',
                'verbose_name_plural': '审批流程模板',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='审批步骤')),
                ('action', models.CharField(choices=[('approve', '同意'), ('reject', '驳回'), ('transfer', '转交'), ('add', '加签')], max_length=20, verbose_name='操作')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workflows.approvalinstance', verbose_name='审批实例')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcessNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('approve', '或签'), ('countersign', '会签')], default='approve', max_length=20, verbose_name='审批类型')),
                ('order', models.IntegerField(default=1, verbose_name='审批顺序')),
                ('approvers', models.ManyToManyField(related_name='approval_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.approvalprocess', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '流程节点定义',
                'verbose_name_plural': '流程节点定义',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.approvalprocess', verbose_name='流程模板'),
        ),
    ]
