# Generated by Django 4.2 on 2026-05-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0002_approvalattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='active', max_length=20, verbose_name='项目状态')),
                ('folder_path', models.CharField(blank=True, max_length=500, verbose_name='文件夹路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='workflows.approvalinstance', verbose_name='关联审批')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('file', models.FileField(upload_to='temp/', verbose_name='文件')),
                ('doc_type', models.CharField(choices=[('contract', '合同'), ('attachment', '附件'), ('report', '报告'), ('other', '其他')], default='attachment', max_length=20, verbose_name='文档类型')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workflows.project', verbose_name='所属项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
