# Generated by Django 4.2 on 2026-05-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_menu_role_user_roles'),
        ('workflows', '0003_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalprocessnode',
            name='approver_roles',
            field=models.ManyToManyField(blank=True, related_name='approval_nodes', to='accounts.role', verbose_name='审批角色'),
        ),
    ]
