# Generated by Django 4.2 on 2026-05-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_approvalprocessnode_approver_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalattachment',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='workflows.approvalrecord', verbose_name='关联审批记录'),
        ),
    ]
