# Generated by Django 4.2 on 2026-05-18 13:33

from django.db import migrations, models
import workflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=workflows.models.attachment_upload_path, verbose_name='附件'),
        ),
    ]
