# Generated by Django 4.2 on 2026-05-18 14:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0007_alter_approvalattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='报价单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('rejected', '已驳回')], default='draft', max_length=16, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='总金额(元)')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='折扣(%)')),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='成交金额(元)')),
                ('construction_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='施工周期(天)')),
                ('warranty_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='质保期(年)')),
                ('notes', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workflows.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('design', '设计费'), ('demolition', '拆除工程'), ('water_electric', '水电工程'), ('tiling', '瓦工工程'), ('carpentry', '木工工程'), ('painting', '油漆工程'), ('main_material', '主材'), ('soft_furnishing', '软装'), ('other', '其他')], default='other', max_length=32, verbose_name='分类')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='规格说明')),
                ('unit', models.CharField(default='项', max_length=16, verbose_name='单位')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='单价(元)')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='小计(元)')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workflows.quotation', verbose_name='报价单')),
            ],
            options={
                'verbose_name': '报价明细',
                'verbose_name_plural': '报价明细',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
