# Generated by Django 4.2 on 2026-05-18 14:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0008_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='分类')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='规格说明')),
                ('unit', models.CharField(default='项', max_length=16, verbose_name='单位')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基准价格(元)')),
                ('fluctuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = 固定价格；10 = 允许上下浮动 10%', max_digits=5, verbose_name='浮动范围(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '价格项目',
                'verbose_name_plural': '价格表',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='price_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='workflows.priceitem', verbose_name='参照价格项目'),
        ),
    ]
